(function(f,u){typeof exports=="object"&&typeof module!="undefined"?u(exports,require("react")):typeof define=="function"&&define.amd?define(["exports","react"],u):(f=typeof globalThis!="undefined"?globalThis:f||self,u(f["react-pinia"]={},f.React))})(this,function(f,u){"use strict";function E(t){return t&&typeof t=="object"&&"default"in t?t:{default:t}}var D=E(u);function C(t,e){if(t===e)return!0;for(var r=0;r<t.length;r++)if(!Object.is(t[r],e[r]))return!1;return!0}function T(t,e){var r=u.useRef({deps:e,obj:void 0,initialized:!1}).current;return(r.initialized===!1||!C(r.deps,e))&&(r.deps=e,r.obj=t(),r.initialized=!0),r.obj}var U=globalThis&&globalThis.__read||function(t,e){var r=typeof Symbol=="function"&&t[Symbol.iterator];if(!r)return t;var n=r.call(t),a,o=[],c;try{for(;(e===void 0||e-- >0)&&!(a=n.next()).done;)o.push(a.value)}catch(s){c={error:s}}finally{try{a&&!a.done&&(r=n.return)&&r.call(n)}finally{if(c)throw c.error}}return o},k=function(){var e=U(u.useState({}),2),r=e[1];return u.useCallback(function(){return r({})},[])},m=k;const Y=t=>Object.prototype.toString.call(t),H="dfv2$@#w0h*das2g3{fa0k]",y=new WeakMap,O=new WeakMap,F="3vlfgh2bh2js@5dlw82960@",b=t=>t>9?`${t}`:`0${t}`,I=t=>Number(t.replace(/[^\d]/g,""))-12457801,J=(t,e="Y-M-D H:m:s")=>{const r=new Date(t),n=""+r.getFullYear(),a=b(r.getMonth()+1),o=b(r.getDate()),c=b(r.getHours()),s=b(r.getMinutes()),i=b(r.getSeconds());return e.replace(/[YMDHS]/gi,g=>{switch(g){case"Y":return n;case"M":return a;case"D":return o;case"H":return c;case"m":return s;case"s":return i;default:return""}})},l=t=>new Map([["[object Function]","function"],["[object Undefined]","undefined"],["[object Boolean]","boolean"],["[object Number]","number"],["[object String]","string"],["[object Array]","array"],["[object Date]","date"],["[object RegExp]","regExp"],["[object Null]","null"],["[object Object]","object"],["[object Symbol]","symbol"],["[object Promise]","promise"]]).get(Y(t));function j(t,e,r){const n=y.get(e);if(n)return n;if(O.has(e))return e;const a=new Proxy(e,{get(o,c,s){const i=Reflect.get(o,c,s);return l(i)==="object"||l(i)==="array"?j(t,i,r):Reflect.get(o,c)},set(o,c,s){if(o[c]===s)return Reflect.get(o,c);const i=Reflect.set(o,c,s);return r(t||c),i},deleteProperty(o,c){const s=Reflect.deleteProperty(o,c);return r(t||c),s}});return y.set(e,a),O.set(a,e),a}const h=()=>Number(J(new Date,"YMDHms"))>I(H+F);function _(t,e,r){(l(t)==="string"&&t===e||l(t)==="array"&&t.includes(e))&&r()}function L(t){return{all:t=t||new Map,on:function(e,r){var n=t.get(e);n?n.push(r):t.set(e,[r])},off:function(e,r){var n=t.get(e);n&&(r?n.splice(n.indexOf(r)>>>0,1):t.set(e,[]))},emit:function(e,r){var n=t.get(e);n&&n.slice().map(function(a){a(r)}),(n=t.get("*"))&&n.slice().map(function(a){a(e,r)})}}}const d=L();var S={exports:{}},p={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var w=Object.getOwnPropertySymbols,z=Object.prototype.hasOwnProperty,A=Object.prototype.propertyIsEnumerable;function W(t){if(t==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(t)}function B(){try{if(!Object.assign)return!1;var t=new String("abc");if(t[5]="de",Object.getOwnPropertyNames(t)[0]==="5")return!1;for(var e={},r=0;r<10;r++)e["_"+String.fromCharCode(r)]=r;var n=Object.getOwnPropertyNames(e).map(function(o){return e[o]});if(n.join("")!=="0123456789")return!1;var a={};return"abcdefghijklmnopqrst".split("").forEach(function(o){a[o]=o}),Object.keys(Object.assign({},a)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}B();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var G=D.default,x=60103;if(p.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var P=Symbol.for;x=P("react.element"),p.Fragment=P("react.fragment")}var Q=G.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,X=Object.prototype.hasOwnProperty,Z={key:!0,ref:!0,__self:!0,__source:!0};function R(t,e,r){var n,a={},o=null,c=null;r!==void 0&&(o=""+r),e.key!==void 0&&(o=""+e.key),e.ref!==void 0&&(c=e.ref);for(n in e)X.call(e,n)&&!Z.hasOwnProperty(n)&&(a[n]=e[n]);if(t&&t.defaultProps)for(n in e=t.defaultProps,e)a[n]===void 0&&(a[n]=e[n]);return{$$typeof:x,type:t,key:o,ref:c,props:a,_owner:Q.current}}p.jsx=R,p.jsxs=R,S.exports=p;const q=S.exports.jsx,M=u.createContext({}),N={},V=({store:t,children:e})=>{const r=m(),n=u.useRef(t),a=T(()=>{const o=c=>{r(),d.emit("update",c)};return Object.keys(n.current).map(c=>{n.current[c]=j(c,n.current[c],o)}),n.current},[]);return q(M.Provider,{value:a,children:e})},$=t=>{const e=m(),r=u.useContext(M);return u.useEffect(()=>{if(h())return()=>{};if(t&&(l(t)==="string"||l(t)==="array")){const n=a=>{_(t,a,e)};d.on("update",n)}else d.on("update",e);return()=>{d.off("update",e)}},[]),r},K=(t,e)=>{const r=JSON.parse(JSON.stringify(e.state()));let n=[];const a=j(null,Object.assign({},e.state()),o);function o(c){d.emit("local",c)}if(N[t]=a,e.actions){n=n.concat(Object.keys(e.actions));try{Object.keys(e.actions).map(c=>{N[t][c]=e.actions&&e.actions[c].bind(a)})}catch{}}if(e.getters){n=n.concat(Object.keys(e.getters));try{Object.keys(e.getters).map(c=>{a[c]=e.getters&&e.getters[c](r)})}catch{}}return c=>{const s=m(),i=a;return u.useEffect(()=>h()?()=>{}:(d.on("local",g=>{if(!n.includes(g)){if(e.getters)try{Object.keys(e.getters).map(v=>{a[v]=e.getters&&e.getters[v](JSON.parse(JSON.stringify(a)))})}catch{}c&&(l(c)==="string"||l(c)==="array")?_(c,g,s):s()}}),()=>{d.off("local")}),[]),i}};f.Provider=V,f.createStore=$,f.defineStore=K,Object.defineProperties(f,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
