(function(s,c){typeof exports=="object"&&typeof module!="undefined"?c(exports,require("react")):typeof define=="function"&&define.amd?define(["exports","react"],c):(s=typeof globalThis!="undefined"?globalThis:s||self,c(s["react-pinia"]={},s.React))})(this,function(s,c){"use strict";function w(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}var x=w(c);function S(e,r){if(e===r)return!0;for(var t=0;t<e.length;t++)if(!Object.is(e[t],r[t]))return!1;return!0}function P(e,r){var t=c.useRef({deps:r,obj:void 0,initialized:!1}).current;return(t.initialized===!1||!S(t.deps,r))&&(t.deps=r,t.obj=e(),t.initialized=!0),t.obj}var R=globalThis&&globalThis.__read||function(e,r){var t=typeof Symbol=="function"&&e[Symbol.iterator];if(!t)return e;var n=t.call(e),o,a=[],u;try{for(;(r===void 0||r-- >0)&&!(o=n.next()).done;)a.push(o.value)}catch(f){u={error:f}}finally{try{o&&!o.done&&(t=n.return)&&t.call(n)}finally{if(u)throw u.error}}return a},E=function(){var r=R(c.useState({}),2),t=r[1];return c.useCallback(function(){return t({})},[])},d=E;const C=e=>e!==null&&typeof e=="object";function T(e){return{all:e=e||new Map,on:function(r,t){var n=e.get(r);n?n.push(t):e.set(r,[t])},off:function(r,t){var n=e.get(r);n&&(t?n.splice(n.indexOf(t)>>>0,1):e.set(r,[]))},emit:function(r,t){var n=e.get(r);n&&n.slice().map(function(o){o(t)}),(n=e.get("*"))&&n.slice().map(function(o){o(r,t)})}}}var b={exports:{}},i={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var v=Object.getOwnPropertySymbols,M=Object.prototype.hasOwnProperty,k=Object.prototype.propertyIsEnumerable;function N(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function U(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var r={},t=0;t<10;t++)r["_"+String.fromCharCode(t)]=t;var n=Object.getOwnPropertyNames(r).map(function(a){return r[a]});if(n.join("")!=="0123456789")return!1;var o={};return"abcdefghijklmnopqrst".split("").forEach(function(a){o[a]=a}),Object.keys(Object.assign({},o)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}U();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var I=x.default,y=60103;if(i.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var m=Symbol.for;y=m("react.element"),i.Fragment=m("react.fragment")}var L=I.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,z=Object.prototype.hasOwnProperty,F={key:!0,ref:!0,__self:!0,__source:!0};function g(e,r,t){var n,o={},a=null,u=null;t!==void 0&&(a=""+t),r.key!==void 0&&(a=""+r.key),r.ref!==void 0&&(u=r.ref);for(n in r)z.call(r,n)&&!F.hasOwnProperty(n)&&(o[n]=r[n]);if(e&&e.defaultProps)for(n in r=e.defaultProps,r)o[n]===void 0&&(o[n]=r[n]);return{$$typeof:y,type:e,key:a,ref:u,props:o,_owner:L.current}}i.jsx=g,i.jsxs=g,b.exports=i;const W=b.exports.jsx,j=c.createContext({}),l=T(),O=new WeakMap,_=new WeakMap;function h(e,r,t){const n=O.get(r);if(n)return n;if(_.has(r))return r;const o=new Proxy(r,{get(a,u,f){const p=Reflect.get(a,u,f);return C(p)?h(e,p,t):Reflect.get(a,u)},set(a,u,f){const p=Reflect.set(a,u,f);return t(e),p},deleteProperty(a,u){const f=Reflect.deleteProperty(a,u);return t(e),f}});return O.set(r,o),_.set(o,r),o}const A=({store:e,children:r})=>{const t=d(),n=c.useRef(e),o=P(()=>{const a=u=>{t(),l.emit("update",u)};return Object.keys(n.current).map(u=>{n.current[u]=h(u,n.current[u],a)}),n.current},[]);return W(j.Provider,{value:o,children:r})},B=e=>{const r=d(),t=c.useContext(j);return c.useEffect(()=>{if(e){const n=o=>{e===o&&r()};l.on("update",n)}else l.on("update",r);return()=>{l.off("update",r)}},[]),t};s.Provider=A,s.createStore=B,Object.defineProperties(s,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
