(function(u,f){typeof exports=="object"&&typeof module!="undefined"?f(exports,require("react")):typeof define=="function"&&define.amd?define(["exports","react"],f):(u=typeof globalThis!="undefined"?globalThis:u||self,f(u["react-pinia"]={},u.React))})(this,function(u,f){"use strict";var J=Object.defineProperty;var Y=(u,f,i)=>f in u?J(u,f,{enumerable:!0,configurable:!0,writable:!0,value:i}):u[f]=i;var x=(u,f,i)=>(Y(u,typeof f!="symbol"?f+"":f,i),i);function i(r){return r&&typeof r=="object"&&"default"in r?r:{default:r}}var S=i(f);function P(r,e){if(r===e)return!0;for(var t=0;t<r.length;t++)if(!Object.is(r[t],e[t]))return!1;return!0}function R(r,e){var t=f.useRef({deps:e,obj:void 0,initialized:!1}).current;return(t.initialized===!1||!P(t.deps,e))&&(t.deps=e,t.obj=r(),t.initialized=!0),t.obj}var E=globalThis&&globalThis.__read||function(r,e){var t=typeof Symbol=="function"&&r[Symbol.iterator];if(!t)return r;var n=t.call(r),s,o=[],a;try{for(;(e===void 0||e-- >0)&&!(s=n.next()).done;)o.push(s.value)}catch(c){a={error:c}}finally{try{s&&!s.done&&(t=n.return)&&t.call(n)}finally{if(a)throw a.error}}return o},C=function(){var e=E(f.useState({}),2),t=e[1];return f.useCallback(function(){return t({})},[])},v=C;const T=r=>r!==null&&typeof r=="object";class k{constructor(){x(this,"events");this.events={}}on(e,t){(this.events[e]||(this.events[e]=[])).push({listener:t})}emit(e,t){this.events[e].forEach(n=>{n.listener(t),e==="once"&&this.off(e,n.listener)})}once(e,t){this.events[e]=this.events[e]||[],this.events[e].push({listener:t,once:!0})}off(e,t){this.events[e]&&(this.events[e]=this.events[e].filter(n=>n.listener!==t))}}var b={exports:{}},l={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var h=Object.getOwnPropertySymbols,M=Object.prototype.hasOwnProperty,N=Object.prototype.propertyIsEnumerable;function U(r){if(r==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(r)}function I(){try{if(!Object.assign)return!1;var r=new String("abc");if(r[5]="de",Object.getOwnPropertyNames(r)[0]==="5")return!1;for(var e={},t=0;t<10;t++)e["_"+String.fromCharCode(t)]=t;var n=Object.getOwnPropertyNames(e).map(function(o){return e[o]});if(n.join("")!=="0123456789")return!1;var s={};return"abcdefghijklmnopqrst".split("").forEach(function(o){s[o]=o}),Object.keys(Object.assign({},s)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}I();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var L=S.default,m=60103;if(l.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var j=Symbol.for;m=j("react.element"),l.Fragment=j("react.fragment")}var z=L.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,F=Object.prototype.hasOwnProperty,W={key:!0,ref:!0,__self:!0,__source:!0};function y(r,e,t){var n,s={},o=null,a=null;t!==void 0&&(o=""+t),e.key!==void 0&&(o=""+e.key),e.ref!==void 0&&(a=e.ref);for(n in e)F.call(e,n)&&!W.hasOwnProperty(n)&&(s[n]=e[n]);if(r&&r.defaultProps)for(n in e=r.defaultProps,e)s[n]===void 0&&(s[n]=e[n]);return{$$typeof:m,type:r,key:o,ref:a,props:s,_owner:z.current}}l.jsx=y,l.jsxs=y,b.exports=l;const A=b.exports.jsx,O=f.createContext({}),p=new k,g=new WeakMap,_=new WeakMap;function w(r,e,t){const n=g.get(e);if(n)return n;if(_.has(e))return e;const s=new Proxy(e,{get(o,a,c){const d=Reflect.get(o,a,c);return T(d)?w(r,d,t):Reflect.get(o,a)},set(o,a,c){const d=Reflect.set(o,a,c);return t(r),d},deleteProperty(o,a){const c=Reflect.deleteProperty(o,a);return t(r),c}});return g.set(e,s),_.set(s,e),s}const B=({store:r,children:e})=>{const t=v(),n=f.useRef(r),s=R(()=>{const o=a=>{t(),p.emit("update",{key:a})};return Object.keys(n.current).map(a=>{n.current[a]=w(a,n.current[a],o)}),n.current},[]);return A(O.Provider,{value:s,children:e})},D=r=>{const e=v(),t=f.useContext(O);return f.useEffect(()=>(r?p.once("update",({key:n})=>{r===n&&e()}):p.once("update",e),()=>{p.off("update",e)}),[]),t};u.Provider=B,u.createStore=D,Object.defineProperties(u,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
